GET http://localhost:8880/ebook/list?page=1&size=4

###


#ptr快捷调出 json方式提交
POST http://localhost:8880/ebook/save
Content-Type: application/json

{
  "id": 34916597428785152,
  "name": "34916",
  "cover": "22222"
}

###

#ptrp快捷 form方式提交
POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###