#测试接口新建一个http文件输入ptr测试get请求 ptrp 带参数请求
#设置Live Templates下
GET http://localhost:8880/hello

#HTTP Client结果验证
 #希望接受json格式 返回的是Hello Word 字符串格式 =》注释掉
 #Accept: application/json
> {%
 client.test("test-hello",function (){
   client.log("测试Hello接口");
   client.log(response.body);
   client.log(JSON.stringify(response.body));
   client.assert(response.status === 200,"返回码不是200");
   client.assert(response.body === "Hello World!","结果验证失败");
 })
%}


###

POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

#id=99&content=new-element
name=TEST
###

GET http://localhost:8880/test/list

###